### ISSUE TITLE
MSBuild issue

### ISSUE THREAD

**Issue by ZeroLP** [tusharjain1082/DiaryJournal.Net#1]
Cool project found whilst surfing through Github, and I thought I should give it a try!

When compiling, I am hit with MSBuild errors where it fails to copy dependencies to output path. 
I found out that the the BaseOutputPath property in the MSBuild config is hard coded to your local drive [here](https://github.com/tusharjain1082/DiaryJournal.Net/blob/f24edc1eed34ecbf353731bfd373493cbe4176bd/DiaryJournal.Net/DiaryJournal.Net.csproj#L65).

I resolved it by removing the property  as I felt it was necessary since the default build path already targets the /bin of the relative project directory.

Hopefully I can contribute more towards this interesting project!

**Comment by tusharjain1082** [comment]
thanks for informing. i did not know that. yes i am making an output of my primary project DiaryJournal.Net to a custom set drive and directory. i have kept my project in my G: Drive and i set the project to output there.

**Comment by ZeroLP** [comment]
If that's the case, you may want to explore copying the output on post-build event with a check based on whether if the directory exists or not.

**Comment by tusharjain1082** [comment]
thanks for the information. i have now set "..\bin\" as the output path of my project DiaryJournal.Net. this is a path internal and relative to the entire solution. now it will automatically output to bin\ path inside the solution. this change will come in effect when i republish an upgraded version of DiaryJournal.Net.

**Comment by ZeroLP** [comment]
Mind asking when you are committing it? Because I'd like to create some PRs for small changes I'm seeking at the moment.
